version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

volumes:
  elastic-storage:

services:
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic-storage:/usr/share/elasticsearch/data:rw   # Persistence data
    networks:
      - web-app-net

  kibana:
    image: kibana:7.9.2
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200     # Optional when standalone
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - web-app-net

##End of Scripts