version: '3.5'

networks:
  web-app-net:
    name: my-web-app-net
    #driver: overlay
    driver: bridge

services:
   webapp:
      image: spring-elastic-starter:1.0
      build:
         context: .
         dockerfile: Dockerfile
      environment:
         elastic.db.cluster-name: docker-cluster
         elastic.db.host: elasticsearch
         elastic.db.port: 9200
         elastic.db.username: root
         elastic.db.password: root@123
         spring.profiles.active: elastic
         management.endpoints.web.exposure.include: health,metrics,httptrace,prometheus
         app.home.logs: /home/logs
         app.upload.dir: /home/downloads
      ports:
         - 8080:8080
      restart: on-failure
      networks:
         - web-app-net

##End of Scripts